import localFont from 'next/font/local';
import { Darker_Grotesque, DM_Sans, Geist, Urbanist } from 'next/font/google';
import './globals.css';
import Header from './components/header/page';
import Footer from './components/Footer/Footer';
import SmoothScroll from './components/Scroll/SmoothScroll';
//const micaroline = localFont({
//  src: "./fonts/micaroline-regular.otf", // ✅ Correct path (inside /app/)
//  variable: "--font-micaroline",
//  display: "swap",
//})

const eulogy = localFont({
  src: '/fonts/EulogyDemo-Regular.ttf',
  display: 'swap',
  variable: '--font-eulogy' // Custom CSS variable
});

//const geistSans = Geist({
//  variable: "--font-geist-sans",
//  subsets: ["latin"],
//})

const darkerGrotesque = Darker_Grotesque({
  variable: '--font-darker-grotesque',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'] // Include required weights
});

const dMSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900']
});

const urbanist = Urbanist({
  variable: '--font-urbanist',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: 'Robel',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    //<html lang="en" className={`${micaroline.variable} ${geistSans.nocturne} ${geistSans.variable} ${darkerGrotesque.variable}`}>
    <html
      lang="en"
      className={`${darkerGrotesque.variable} ${dMSans.variable} ${eulogy.variable} ${urbanist.variable}`}
    >
      <body className="antialiased">
        <SmoothScroll />
        <Header />
        {children}
        <div className="container mx-auto px-8">
          <Footer />
        </div>
      </body>
    </html>
  );
}
